nome = str(input('Digite se nome completo: ')).strip()
print('Analisando seu nome...')
print('seu nome em maiusculo é {}'.format(nome.upper()))
print('seu nome em minusculo é {}'.format(nome.lower()))
print('seu nome contem {} letras'.format(len(nome) -nome.count(' ')))
print('seu primeiro nome  tem {}'.format(nome.find(' ')))
separa = nome.split()
print('seu primeiro nome é {}  e ele tem {} letras'.format(separa[0], len(separa[0])))